### ISSUE TITLE
need to use cross_env under windows

### ISSUE THREAD

**Issue by froeb** [royandco/static-starter#46]
in order that this works under windows, you need to change/add in config.json:

  "scripts": {
    "dev": "cross-env NODE_ENV=development LANG=en netlify dev",
    "dev:es": "cross-env ENV NODE_ENV=development LANG=es netlify dev",
    "build": "cross-env ENV NODE_ENV=production gulp build --production",
    [...]
    "build:serve": "cross-env ENV NODE_ENV=production gulp build:serve --production"
  },
  "dependencies": {
[...]
    "cross-env": "^7.0.2",

**Comment by roybarber** [comment]
Ah thank you! Feel free to submit a PR :)

**Comment by froeb** [comment]
Thanks roy.

I plan to create a superset of your project that includes all the good ideas I see in a handful similar projects. My main addition would be the integration of eleventy as static site generator and may also posthtml (not sure about that one), that would give more flexibility. I see no combination of gulp, tailwinds and eleventy yet (only projects with two of these three variables). 

If you like, you can implement my additions in your project or I can create a fork.

Danke und alles Gute
Kai Froeb, München
Handy: 0175/5860391
Http://Kai.froeb.net

Ps: Diese Mail von meinem IPhone aus gesendet. Ich bitte daher die Kürze und evtl. Tipp- und Formatierungsfehler zu entschuldigen.
