### ISSUE TITLE
CSS file not copying into /dist/assets/css on build

### ISSUE THREAD

**Issue by evolve2k** [royandco/static-starter#47]
When I spin up the server  with $ npm run dev it was very clear that the CSS was not loading. Note I have not yet made any changes to the repo.  Here's [how it looks as deployed](https://60d2a508b37c430008b08059--amorc-static.netlify.app/).

![Fullscreen_23_6_21__11_57_am](https://user-images.githubusercontent.com/114459/123025732-364a2880-d41a-11eb-93d1-3b0dca700eed.jpg)

Sure enough looking in dist after running npm run build and the css is not generating.

![main_css_—_amorc-static-starter](https://user-images.githubusercontent.com/114459/123025347-a73d1080-d419-11eb-9ce7-78c6d388207a.jpg)

**Can you work out why main.css is not compiling into /dist?**

**For anyone else following:**
The web console also provided this error:

    The resource from “http://localhost:8888/assets/css/main.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

Which some web searching revealed usually occurs when a file is not found.

**Comment by evolve2k** [comment]
Ok it looks like it's an issue with the [tailwind JIT commit](https://amorc.org.au/admin04559/designdashboard.php?adkfj7al0=lg3CgGNWAVJPIpong4ukSwJcfz8aytoU3dAFwQHQoWM).

I wound back to the commit before it and was able to build everything correctly locally.

WEIRDLY.. once I then wound forward to main again, now the CSS is there, locally.

There is still issues when this deploys as I shared before [[example](https://60d2a508b37c430008b08059--amorc-static.netlify.app/)]

**Comment by evolve2k** [comment]
**WORKAROUND: For anyone wanting to use this starter kit out of the box before this is fixed, roll back to the commit before tailwind JIT was added and use that as every thing works out of the box and it deploys successfully.**

**Comment by roybarber** [comment]
@evolve2k This is now resolved. Tailwind updated to 2.2 where JIT is now part of the release.
