### ISSUE TITLE
Disabled input

### ISSUE THREAD

**Issue by roybarber** [royandco/static-starter#5]
Apart from the hover icon, theres no real difference to show the state of the box. We need to improve this. Add a variable for state color if needed/not there already.

**Comment by holliepearson** [comment]
![screen shot 2017-03-20 at 13 45 52](https://cloud.githubusercontent.com/assets/22280756/24102347/8d80c73e-0d73-11e7-9a38-978b90013a1c.png)

Darkened normal input background by 10%. This look suitable @roybarber ?
